_wandb:
    value:
        cli_version: 0.23.1
        e:
            6c9tq8rb1cklo4qhqiybl30vp3x3paly:
                args:
                    - --data
                    - mimic-iv-ecg=../dataset/mimic-ecg.npy
                    - --out
                    - checkpoints/
                    - --config
                    - ViTS_mimic
                    - --amp
                    - bfloat16
                    - --wandb
                codePath: LeJEPA-ECG/pretrain.py
                codePathLocal: pretrain.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1499487559680"
                        used: "13235240960"
                email: jariysser@gmail.com
                executable: /home/yasser.eljarida/lustre/recsys-y8xnv0gztug/users/yasser.eljarida/.conda/conda_envs/jepa-ecg/bin/python
                git:
                    commit: ce13296318972b8e853a9a94de5ecd5685047080
                    remote: https://github.com/YasserElj/MY_ECG.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1d14cc8f-3a25-442d-1b38-bb4a9dfa3e8c
                host: slurm-a100-gpu-h22a2-u18-sv
                memory:
                    total: "1081229176832"
                os: Linux-4.18.0-553.74.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /srv/lustre01/project/recsys-y8xnv0gztug/users/yasser.eljarida/code/MY_ECG/LeJEPA-ECG/pretrain.py
                python: CPython 3.11.14
                root: /srv/lustre01/project/recsys-y8xnv0gztug/users/yasser.eljarida/code/MY_ECG/LeJEPA-ECG
                slurm:
                    cluster_name: slurm
                    conf: /var/spool/slurm/conf-cache/slurm.conf
                    cpus_on_node: "32"
                    cpus_per_task: "32"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: recsys-y8xnv0gztug-default-gpu
                    job_cpus_per_node: "32"
                    job_end_time: "1764927558"
                    job_gid: "1853000513"
                    job_gpus: "3"
                    job_id: "5425006"
                    job_name: lejepa_ecg_pretrain
                    job_nodelist: slurm-a100-gpu-h22a2-u18-sv
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: default gpu
                    job_start_time: "1764841158"
                    job_uid: "1853044386"
                    job_user: yasser.eljarida
                    jobid: "5425006"
                    localid: "0"
                    mem_per_node: "256000"
                    mpi_type: pmi2
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: slurm-a100-gpu-h22a2-u18-sv
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /srv/lustre01/project/recsys-y8xnv0gztug/users/yasser.eljarida/code/MY_ECG/LeJEPA-ECG
                    submit_host: slurm-login-h23d5-u37-svn2.cloud.um6p.ma
                    task_pid: "26364"
                    tasks_per_node: "1"
                    topology_addr: slurm-a100-gpu-h22a2-u18-sv
                    topology_addr_pattern: node
                    tres_per_task: cpu:32
                startedAt: "2025-12-04T09:40:21.575215Z"
                writerId: 6c9tq8rb1cklo4qhqiybl30vp3x3paly
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
amplitude_scale:
    value:
        - 0.8
        - 1.2
attn_dropout:
    value: 0
batch_size:
    value: 1024
bias:
    value: true
channel_size:
    value: 5000
channels:
    value:
        - I
        - II
        - III
        - AVR
        - AVL
        - AVF
        - V1
        - V2
        - V3
        - V4
        - V5
        - V6
checkpoint_interval:
    value: 10000
crop_scale:
    value:
        - 0.5
        - 1
datasets:
    value:
        mimic-iv-ecg: 1
depth:
    value: 8
dim:
    value: 384
dropout:
    value: 0
final_learning_rate:
    value: 1e-06
gradient_accumulation_steps:
    value: 1
gradient_clip:
    value: 1
lambda:
    value: 0.02
layer_scale_eps:
    value: 0
learning_rate:
    value: 0.001
learning_rate_warmup_steps:
    value: 5000
mlp_ratio:
    value: 4
noise_std:
    value: 0.05
norm_eps:
    value: 1e-06
num_heads:
    value: 6
num_params:
    value: 19558528
num_registers:
    value: 1
num_slices:
    value: 1024
num_views:
    value: 4
opt_betas:
    value:
        - 0.9
        - 0.999
opt_eps:
    value: 1e-08
patch_size:
    value: 25
proj_dim:
    value: 128
proj_hidden_dim:
    value: 2048
qkv_bias:
    value: false
sampling_frequency:
    value: 500
steps:
    value: 100000
wandb_log_interval:
    value: 10
wandb_project:
    value: LeJEPA-ECG
wandb_viz_interval:
    value: 1000
weight_decay:
    value: 0.05
